### ISSUE TITLE
socks4支持

### ISSUE THREAD

**Issue by wdhwg001** [GameXG/TcpRoute#13]
RT。socks4支持对于IE等浏览器是必要的，而且TcpRoute当前也的确没有用到socks5的udp功能。

**Comment by GameXG** [comment]
socks4 和 socks5 的区别很小，不过这个需要重构后加入。

**Comment by GameXG** [comment]
已实现。

**Comment by GameXG** [comment]
但是并不建议使用 socks4 ，测试chrome 不支持 socks4a 扩展，无法使用远端dns解析。
