### ISSUE TITLE
内置的ShadowSocks。

### ISSUE THREAD

**Issue by wdhwg001** [GameXG/TcpRoute#15]
…不然就要开多个shadowsocks服务，然后在TcpRoute里设置多个端口了。因为ShadowSocks本身使用Py完成，所以或许可以整合一下…
然而这是个坑，整合了肯定会有人叫嚷着求整合ss://，求整合二维码一类的…认真决策一下好了…

**Comment by GameXG** [comment]
有计划整合 ss ，但是 ss协议没弄过，需要时间了...

**Comment by GameXG** [comment]
放弃了内置支持 shadowsocks 的计划。

shadowsocks 并未完整的实现 socks5 协议，造成测速结果并不准确。

通过下面的补丁暂时缓解了一部分问题，但是由于 shadowsocks 协议本身的问题造成无法同步的获得测速结果。

代码：https://github.com/GameXG/shadowsocks-windows/commit/50309a0fe358245dfbd0d9d5fb2d66654dba8cee
二进制发布：http://www.chenwang.net/2015/07/27/shadowsocks-windows-%e4%bf%ae%e6%94%b9%e7%89%88/
