### ISSUE TITLE
对dns错误页的采集，以及新的dns策略

### ISSUE THREAD

**Issue by wdhwg001** [GameXG/TcpRoute#20]
可以尝试查询不存在的域名以采集域名错误页的ip，应对某些跳转至错误页的污染。

另外，可以尝试使用udp查询dns，并将前后返回的2个udp结果作为正确结果，同时进行尝试，并把失败的一个丢入dns污染列表。
PS: 100似乎少了点，也的确需要新的机制了…

**Comment by GameXG** [comment]
有去除纠错页面的功能

https://github.com/GameXG/TcpRoute/blob/master/dnslib/__init__.py#L230

100 指的是？

**Comment by GameXG** [comment]
在刚启动时异常IP可能并没有采集齐全，所以可能会出现域名纠错页面，采集到后就会屏蔽掉纠错页面了。

**Comment by wdhwg001** [comment]
无妨，我蠢了…
